;; This logfile was generated automatically by `xindy'
;; at 02.08.2020  07:57:16
;; Indexstyle: "/var/folders/4n/jnlz0qvx39qdxmjjq0xpqftw0000gn/T/KhbcmZg6oj", Rawindex: "/var/folders/4n/jnlz0qvx39qdxmjjq0xpqftw0000gn/T/t8bP6TdsoD", Output: "memoria.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€¼" -> "G"